version: '3'

services:
  sfeth:
    image: 080706913315.dkr.ecr.us-east-1.amazonaws.com/sftest:latest
    ports:
      - target: 13042
        x-aws-protocol: https

x-aws-cloudformation:
  Resources:
    Sfeth13042TargetGroup:
      Properties:
        ProtocolVersion: GRPC
        Protocol: HTTPS
    Sfeth13042Listener:

      Properties:
        Protocol: HTTPS
        SslPolicy: "ELBSecurityPolicy-2016-08"
        Certificates:
          CerfiticateArn: 1234


