version: '3'

services:
  sfeth:
    image: 080706913315.dkr.ecr.us-east-1.amazonaws.com/sftest:latest
    ports:
      - 13042:13042
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8547"]
      interval: 90s
      timeout: 10s
      retries: 5

x-aws-cloudformation:
  Resources:
    SfethTCP13042TargetGroup:
      Properties:
        HealthCheckProtocol: HTTP
        HealthCheckPath: /
        HealthCheckPort: 8547

