version: '3'

services:
  sfeth:
    image: 080706913315.dkr.ecr.us-east-1.amazonaws.com/sftest:latest
    ports:
      # for local testing
      - 13042:13042
      - target: 13042
        x-aws-protocol: https

x-aws-cloudformation:
  Resources:
    SfethTaskDefinition:
      Properties:
        Cpu: 1024
        Memory: 2048
    Sfeth13042TargetGroup:
      Properties:
        ProtocolVersion: GRPC
        Protocol: HTTP
        HealthCheckPath: /sf.firehose.v1.Stream/Blocks
        Matcher:
          GrpcCode: 0-99

    Sfeth13042Listener:
      Properties:
        Protocol: HTTPS
        SslPolicy: "ELBSecurityPolicy-2016-08"
        Certificates:
          - CertificateArn: arn:aws:acm:us-east-1:080706913315:certificate/9ffb3b2c-474f-43cd-aa43-2683dde7f38f


